version: '2'
services:
  clickhouse:
    image: yandex/clickhouse-server
    hostname: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  dev:
    build: .
    volumes:
     - .:/usr/app/
    ports:
      - 8080:8080
    environment:
      - DBT_HOST=${CLICKHOUSE_HOST}
      - DBT_USER=${CLICKHOUSE_USER}
      - DBT_PASSWORD=${TF_VAR_clickhouse_password}
