config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True



clickhouse_starschema:
  outputs:
    dev:
      type: clickhouse
      schema: db_oracle
      host: 51.250.66.143
      port: 8123
      user: default
      verify: False
    ci:
      type: clickhouse
      host: clickhouse
      port: 8123
      schema: db_oracle
      threads: 4
  target: dev



