version: 2

sources:
  - name: oracle_source
    schema: db_oracle
    tables:
      - name: INCOMING_MESSAGES
        identifier: db_oracle_raw__stream_INCOMING_MESSAGES  # Фактическое имя таблицы в базе данных
        columns:
          - name: _airbyte_raw_id
            data_type: string
          - name: _airbyte_data
            data_type: string
          - name: _airbyte_extracted_at
            data_type: datetime64
          - name: _airbyte_loaded_at
            data_type: nullable